all:
	g++ -std=c++11 -I./rapidjson RapidjsonExample.cc -o RapidjsonExample
	g++ -std=c++11 -I./rapidjson testRapidjson.cc -o testRapidjson
	g++ -std=c++11 -I./rapidjson parseJsonFromFile.cc -o parseJsonFromFile
	g++ -std=c++11 -I./rapidjson goThroughJson.cc -o goThroughJson
clean:
	rm -rf RapidjsonExample testRapidjson parseJsonFromFile
